format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiWincLite}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_DRIVER_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Ethernet Mode}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'false'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_SELECT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: '7'}
  - type: Combo
    attributes: {id: DRV_WIFI_WINC_LOG_LEVEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: DRV_WIFI_WINC_RTOS_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_RTOS_TASK_PRIORITY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: String
    attributes: {id: DRV_WIFI_WINC_SPI_INST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: drv_spi_0}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_SPI_INST_IDX}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: '0'}
  - type: File
    attributes: {id: DRV_WIFI_WINC_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_USE_SYS_DEBUG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWincLite, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_USE_TCPIP_STACK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: File
    attributes: {id: WDRV_WINC_ETHERNET_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WDRV_WINC_ETHERNET_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WDRV_WINC_HOST_FILE_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_HOST_FILE_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_HTTPPROVCTX_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_HTTPPROVCTX_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_MAC_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: WDRV_WINC_SOCKET_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_SOCKET_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_SSL_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WDRV_WINC_SSL_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_3_LITE_WINC_M2M_SOCKET_HOST_IF_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_3_LITE_WINC_M2M_SSL_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_3_LITE_WINC_SOCKET_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: WIFI_WINC1500_19_7_3_LITE_WINC_SOCKET_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvWincMac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: lib_azure_rtos_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: AZURE_MAC_Dependency}
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: DirectDependency
    attributes: {id: spi}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_spi_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_spi}
- type: ElementPosition
  attributes: {x: '298', y: '326', id: drvWifiWincLite}
