format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: EVIC_1_ENABLE_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_ENABLE_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_PRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_PRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_1_SUBPRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_1_SUBPRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_ENABLE_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: EVIC_4_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: TIMER_1_InterruptHandler}
  - type: Boolean
    attributes: {id: EVIC_4_PRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_PRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Boolean
    attributes: {id: EVIC_4_SUBPRIORITY_GENERATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_4_SUBPRIORITY_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_1ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_2ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_3ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_4ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_5ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_6ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Combo
    attributes: {id: EVIC_PRIORITY_7ATTRIBUTE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: AUTO}
  - type: Boolean
    attributes: {id: EVIC_SRS_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Hex
    attributes: {id: PMD4_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '268370430'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '252510208'}
  - type: Hex
    attributes: {id: PMD7_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_A_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_A_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1024'}
  - type: Hex
    attributes: {id: SYS_PORT_B_ANSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '256'}
  - type: Hex
    attributes: {id: SYS_PORT_B_CNPU}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_B_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_B_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '256'}
  - type: Hex
    attributes: {id: SYS_PORT_E_ANSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '8192'}
  - type: Hex
    attributes: {id: SYS_PORT_E_CNPU}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_E_LAT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Hex
    attributes: {id: SYS_PORT_E_TRIS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: 'true'}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: TIMER_1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: TIMER_1_InterruptHandler}
  - type: Boolean
    attributes: {id: TIMER_1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: 'true'}
  - type: Boolean
    attributes: {id: TMR1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ThreadX, value: 'true'}
  - type: Integer
    attributes: {id: TMR1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '60000000'}
  - type: KeyValueSet
    attributes: {id: clkSvcMode}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: core}
