configName: pic32mk_mcj_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MK0512MCJ064
projectName: ''
settings:
  PackageFilter: azure_rtos;bsp;core;csp;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.6.125\atdf\PIC32MK0512MCJ064.atdf
