configName: sam_a5d2_xult
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMA5D27
projectName: ''
settings:
  PackageFilter: azure_rtos;bsp;core;csp;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.53\atdf\ATSAMA5D27.atdf
